minggu7/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Backend'], function()
{
    Route::resource('dashboard', 'DashboardController');
    Route::resource('pendidikan', 'PendidikanController');
    Route::resource('pengalaman_kerja', 'PengalamanKerjaController');
});

minggu7/app/PengalamanKerja.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PengalamanKerja extends Model
{
    protected $table = 'pengalaman_kerja';
    protected $primaryKey = 'id';
    protected $fillable = [
        'nama', 'jabatan', 'tahun_masuk', 'tahun_keluar'
    ];
}

minggu7/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

minggu7/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

minggu7/app/Http/Controllers/PendidikanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PendidikanController extends Controller
{
    //
}

minggu7/app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.layouts.dashboard');
    }
}

minggu7/app/Http/Controllers/backend/PengalamanKerjaController.php
<?php

namespace App\Http\Controllers;
namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class PengalamanKerjaController extends Controller
{
    public function index()
    {
        $pengalaman_kerja = DB::table('pengalaman_kerja')->get();
        return view('backend.pengalaman_kerja.index', compact('pengalaman_kerja'));
    }

    public function create()
    {
        $pengalaman_kerja = null;
        return view('backend.pengalaman_kerja.create', compact('pengalaman_kerja'));
    }

    public function store(Request $request)
    {
        DB::table('pengalaman_kerja')->insert([
            'nama' => $request->nama,
            'jabatan' => $request->jabatan,
            'tahun_masuk' => $request->tahun_masuk,
            'tahun_keluar' => $request->tahun_keluar
        ]);

        return redirect()->route('pengalaman_kerja.index')
                        ->with('success','Data Pengalaman Kerja baru telah berhasil disimpan.');
    }

    public function edit($id)
    {
        $pengalaman_kerja = DB::table('pengalaman_kerja')->where('id',$id)->first();
        return view('backend.pendidikan.create', compact('pengalaman_kerja'));
    }
    public function update(Request $request){
        DB::table('pengalaman_kerja')->where('id', $request->id)->update([
            'nama' => $request->nama,
            'jabatan' => $request->jabatan,
            'tahun_masuk' => $request->tahun_masuk,
            'tahun_keluar' => $request->tahun_keluar
        ]);
        return redirect()->route('pengalaman_kerja.index')
                        ->with('success','Data Pengalaman Kerja baru berhasil diperbarui.');
    }

    public function destroy($id)
    {
        DB::table('pengalaman_kerja')->where('id',$id)->delete();
        return redirect()->route('pengalaman_kerja.index')
                        ->with('success','Data Pengalaman Kerja berhasil dihapus.');
    }
}

minggu7/resources/views/backend/layouts/dashboard.blade.php
@extends('backend/layouts.template')

@section('content')
<!--main content start-->
<section id="main-content">
      <section class="wrapper">
        <!--overview start-->
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
              <li><i class="fa fa-laptop"></i>Dashboard</li>
            </ol>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box blue-bg">
              <i class="fa fa-cloud-download"></i>
              <div class="count">6.674</div>
              <div class="title">Download</div>
            </div>
            <!--/.info-box-->
          </div>
          <!--/.col-->

          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box brown-bg">
              <i class="fa fa-shopping-cart"></i>
              <div class="count">7.538</div>
              <div class="title">Purchased</div>
            </div>
            <!--/.info-box-->
          </div>
          <!--/.col-->

          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box dark-bg">
              <i class="fa fa-thumbs-o-up"></i>
              <div class="count">4.362</div>
              <div class="title">Order</div>
            </div>
            <!--/.info-box-->
          </div>
          <!--/.col-->

          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box green-bg">
              <i class="fa fa-cubes"></i>
              <div class="count">1.426</div>
              <div class="title">Stock</div>
            </div>
            <!--/.info-box-->
          </div>
          <!--/.col-->

        </div>
        <!--/.row-->


      </section>
      <div class="text-right">
        <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </section>
    <!--main content end-->
    @endsection

minggu7/resources/views/backend/layouts/sidebar.blade.php
<!--sidebar start-->
<aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="active">
            <a class="" href="index.html">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
          </li>
          <li class="active">
            <a class="" href="index.html">
                          <i class="icon_profile"></i>
                          <span>Profile</span>
                      </a>
          </li>

          <li class="sub-menu">
            <a href="javascript:;" class="">
                          <i class="icon_document_alt"></i>
                          <span>Riwayat Hidup</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{{url('pendidikan')}}">Pendidikan</a></li>
              <li><a class="" href="{{url('pengalaman_kerja')}}">Pengalaman Kerja</a></li>
            </ul>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

minggu7/resources/views/backend/pendidikan/create.blade.php
@extends('backend/layouts.template')

@section('content')
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_document_alt"></i>Riwayat Hidup</h3>
            <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{{ url('dashboard')}}">Home</a></li>
                <li><i class="icon_document_alt"></i>Riwayat Hidup</li>
                <li><i class="fa fa-files-o"></i>Pengalaman Kerja</li>
            </ol>
            </div>
        </div>
        <!--Form validation-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                    {{ isset($admin_lecturer) ? 'Mengubah' : 'Menambahkan' }} Pengalaman Kerja
                    </header>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input. <br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <div class="panel-body">
                        <div class="form">
                            <form class="form-validate form-horizontal" id="pengalaman_kerja_form" method="POST"
                            action="{{ isset($pengalaman_kerja) ? route('pengalaman_kerja.update', $pengalaman_kerja->id) :
                            route('pengalaman_kerja.store') }}">
                            {!! csrf_field() !!}
                            {!! isset($pengalaman_kerja) ? method_field('PUT') : ''!!}
                            <input type="hidden" name="id" value="{{ $pengalaman_kerja->id}}"> </br>
                            <div class="form-group">
                            <label for="cname" class="control-label col-lg-2">Nama Perusahaan <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="nama" name="nama" minlength="5" type="text"
                                value="{{ isset($pengalaman_kerja) ? $pengalaman_kerja->nama : ''}}"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="cname" class="control-label col-lg-2"> Jabatan <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="jabatan" name="jabatan" minlength="2" type="text"
                                value="{{ isset($pengalaman_kerja) ? $pengalaman_kerja->jabatan : ''}}"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="curl" class="control-label col-lg-2"> Tahun Masuk <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="tahun_masuk" name="tahun_masuk" type="text"
                                value="{{ isset($pengalaman_kerja) ? $pengalaman_kerja->tahun_masuk : ''}}"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="curl" class="control-label col-lg-2"> Tahun Selesai <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="tahun_keluar" name="tahun_keluar" type="text"
                                value="{{ isset($pengalaman_kerja) ? $pengalaman_kerja->tahun_keluar : ''}}"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit">Save</button>
                                    <a href="{{route('pengalaman_kerja.index')}}"><button class="btn btn-default"
                                    type ="button"> Cancel</button></a>
                                </div>
                            </div>
                            </form>
                        </div>
                       
                    </div>
                </section>
            </div>
        </div>
 
    </section>
</section>
@endsection
@push('content-css')
<link href="{{asset('backend/css/bootstrap-datepicker.css')}}" rel="stylesheet"/>
@endpush
@push('content-js')
<script src="{{asset('backend/js/bootstrap-datepicker.css')}}"></script>
<script type="text/javascript">
    $('#tahun_masuk').datepicker({
        format: "yyyy",
        viewMode: "years",
        minViewMode: "years"
    });
    $('#tahun_keluar').datepicker({
        format: "yyyy",
        viewMode: "years",
        minViewMode: "years"
    });
</script>
@endpush

minggu7/resources/views/backend/pendidikan/index.blade.php
@extends('backend/layouts.template')

@section('content')
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_document_alt"></i>Riwayat Hidup</h3>
            <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{{ url('dashboard')}}">Home</a></li>
                <li><i class="icon_document_alt"></i>Riwayat Hidup</li>
                <li><i class="fa fa-files-o"></i>Pengalaman Kerja</li>
            </ol>
            </div>
        </div>
        <!--Form validation-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                    Pengalaman Kerja
                    </header>
                    <div class="panel-body">
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                        @endif
                        <a href="{{ route('pengalaman_kerja.create')}}"><button class="btn btn-primary"
                        type="button"><i class="fa fa-plus"> Tambah</i></button></a>
                        <br> <br>
                        <table class="table table-striped table-advance table hover">
                            <tbody>
                                <tr>
                                    <th><i class="icon_bag"></i> Nama</th>
                                    <th><i class="icon_document"></i> Jabatan</th>
                                    <th><i class="icon_calender"></i> Tahun Masuk</th>
                                    <th><i class="icon_calender"></i> Tahun Selesai</th>
                                    <th><i class="icon_cogs"></i> Action</th>
                                </tr>
                                @foreach ($pengalaman_kerja as $item)
                                <tr>
                                    <td>{{$item->nama}}</td>
                                    <td>{{$item->jabatan}}</td>
                                    <td>{{$item->tahun_masuk}}</td>
                                    <td>{{$item->tahun_keluar}}</td>
                                    <td>
                                    <div class="btn-group">
                                            <a class="btn btn-warning" href="{{ route('pengalaman_kerja.edit', $item->id)}}">
                                                <i class="fa fa-edit"></i></a> 
                                                <button type="submit" class="btn btn-danger">
                                            <i class="fa fa-trash-o"></i></button>
                                    </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
        <!--page end-->
    </section>
</section>
@endsection

minggu7/resources/views/backend/pengalaman_kerja/create.blade.php
@extends('backend/layouts.template')

@section('content')
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_document_alt"></i>Riwayat Hidup</h3>
            <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{{ url('dashboard')}}">Home</a></li>
                <li><i class="icon_document_alt"></i>Riwayat Hidup</li>
                <li><i class="fa fa-files-o"></i>Pengalaman Kerja</li>
            </ol>
            </div>
        </div>
        <!--Form validation-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                    {{ isset($admin_lecturer) ? 'Mengubah' : 'Menambahkan' }} Pengalaman Kerja
                    </header>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input. <br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <div class="panel-body">
                        <div class="form">
                            <form class="form-validate form-horizontal" id="pengalaman_kerja_form" method="POST"
                            action="{{ route('pengalaman_kerja.store')}}">
                            {!! csrf_field() !!}
                            <div class="form-group">
                            <label for="cname" class="control-label col-lg-2">Nama Perusahaan <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="nama" name="nama" minlength="5" type="text"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="cname" class="control-label col-lg-2"> Jabatan <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="jabatan" name="jabatan" minlength="2" type="text"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="curl" class="control-label col-lg-2"> Tahun Masuk <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="tahun_masuk" name="tahun_masuk" type="text"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="curl" class="control-label col-lg-2"> Tahun Selesai <span
                                class="required">*</span></label>
                            <div class="col-lg-10">
                                <input class="form-control" id="tahun_keluar" name="tahun_keluar" type="text"
                                required/>
                            </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit">Save</button>
                                    <a href="{{route('pengalaman_kerja.index')}}"><button class="btn btn-default"
                                    type ="button"> Cancel</button></a>
                                </div>
                            </div>
                            </form>
                        </div>
                       
                    </div>
                </section>
            </div>
        </div>
 
    </section>
</section>
@endsection
@push('content-css')
<link href="{{asset('backend/css/bootstrap-datepicker.css')}}" rel="stylesheet"/>
@endpush
@push('content-js')
<script src="{{asset('backend/js/bootstrap-datepicker.css')}}"></script>
<script type="text/javascript">
    $('#tahun_masuk').datepicker({
        format: "yyyy",
        viewMode: "years",
        minViewMode: "years"
    });
    $('#tahun_keluar').datepicker({
        format: "yyyy",
        viewMode: "years",
        minViewMode: "years"
    });
</script>
@endpush

minggu7/resources/views/backend/pengalaman_kerja/index.blade.php
@extends('backend/layouts.template')

@section('content')
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_document_alt"></i>Riwayat Hidup</h3>
            <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{{ url('dashboard')}}">Home</a></li>
                <li><i class="icon_document_alt"></i>Riwayat Hidup</li>
                <li><i class="fa fa-files-o"></i>Pengalaman Kerja</li>
            </ol>
            </div>
        </div>
        <!--Form validation-->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                    Pengalaman Kerja
                    </header>
                    <div class="panel-body">
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                        @endif
                        <a href="{{ route('pengalaman_kerja.create')}}"><button class="btn btn-primary"
                        type="button"><i class="fa fa-plus"> Tambah</i></button></a>
                        <br> <br>
                        <table class="table table-striped table-advance table hover">
                            <tbody>
                                <tr>
                                    <th><i class="icon_bag"></i> Nama</th>
                                    <th><i class="icon_document"></i> Jabatan</th>
                                    <th><i class="icon_calender"></i> Tahun Masuk</th>
                                    <th><i class="icon_calender"></i> Tahun Selesai</th>
                                    <th><i class="icon_cogs"></i> Action</th>
                                </tr>
                                @foreach ($pengalaman_kerja as $item)
                                <tr>
                                    <td>{{$item->nama}}</td>
                                    <td>{{$item->jabatan}}</td>
                                    <td>{{$item->tahun_masuk}}</td>
                                    <td>{{$item->tahun_keluar}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <form action="{{route ('pengalaman_kerja.destroy', $item->id)}}"
                                            method="POST">
                                            <a class="btn btn-warning" href="{{ route('pengalaman_kerja.edit', $item->id)}}">
                                                <i class="fa fa-edit"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"
                                            onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">
                                            <i class="fa fa-trash-o"></i></button>
                                            </form>
                                        </div>
                                        </div>    
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
        <!--page end-->
    </section>
</section>
@endsection